apiVersion: v1
kind: Secret
metadata:
  name: librechat-credentials-env
  namespace: default
type: Opaque
stringData:
  # Claves de seguridad para LibreChat
  CREDS_KEY: "8ba034aaf4ed0d08181d655076fc33468c677f7985d608616ec85c8af15ede98"
  JWT_SECRET: "6d5c804d16ec56d1f828e01dee484cbddaf052bedde40542ea156c474f50ffab"
  JWT_REFRESH_SECRET: "2a2205a497c869f57504638dacca42109251e60f75b6f537bd4dbedb78b0058b"
  
  # Clave maestra para Meilisearch
  MEILI_MASTER_KEY: "f89a8f7957d7608e112040f4156972bc"
  
  # API Key de OpenAI (reemplaza con tu clave real)
  OPENAI_API_KEY: "sk-tu-api-key-aqui"